# Generated by Django 4.2.7 on 2023-11-03 13:43

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_vacancies_min_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='updated_at',
            field=models.DateField(null=True, validators=[vacancies.models.check_data_not_past]),
        ),
    ]
